### ISSUE TITLE
[Question] "This project is: -unmaintained"

### ISSUE THREAD

**Issue by HGStyle** [ItalianApkDownloader/GD_Editor_2_21#2]
"This project is: - unmaintained" from the README.md file.
Does this means there will be no more updates made to GDPS Editor 2.2 ?

**Comment by D4M5** [comment]
Even without all that there are no updates planned for the GDPS. The actual release of GD 2.2 is right around the corner (in like a month or less), and when 1.4 was released it was dubbed as "The final update". So indeed, no updates are planned.

**Comment by HGStyle** [comment]
Will there be GDPS Editor 2.3 when some leaks will be found about it ?

**Comment by D4M5** [comment]
@HGStyle just check the server for any questions you have

but in simple terms yeah there might be a revival if some 2.3 stuff pops up, although it's not likely

**Comment by EDJCS** [comment]
> "Este proyecto: - no está mantenido" del archivo README.md. ¿Significa esto que no se realizarán más actualizaciones en GDPS Editor 2.2?
